# serverless.yml

service: weather-api

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: weather_endpoint.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1
  apiGateway:
    shouldStartNameWithService: true

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /api/v1/weather/{location}
          method: get
      - http:
          path: /api/v1/weather/{location}/forecast
          method: get
      - http:
          path: /api/v1/gold
          method: get
      - http:
          path: /api/v1/fuel
          method: get
      - http:
          path: /api/v1/hdfcbond
          method: get