# serverless.yml

service: weather-api

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: weather_endpoint.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'